
import type { Event, Ticket, VendorEvent } from '@/lib/types';

// Note: All image paths are now relative to the /public folder.
// For example, '/assets/event-1.jpg' maps to 'public/assets/event-1.jpg'.

export const sampleEvents: Event[] = [
  {
    id: 'evt-001',
    name: 'Summer Music Fest 2024',
    description: 'An unforgettable weekend of live music under the stars. Featuring top artists from rock, pop, and electronic genres.',
    date: '2024-08-15T18:00:00Z',
    time: '6:00 PM',
    location: 'Greenfield Park Amphitheater',
    category: 'Music',
    price: 75.00,
    imageUrl: 'https://picsum.photos/seed/musicfest/600/400',
    imageHint: 'music festival',
    organizer: 'SoundWave Productions',
    vendorId: 'vendor-01',
    status: 'approved',
  },
  {
    id: 'evt-002',
    name: 'Gourmet Food Fair',
    description: 'Explore a world of flavors with top chefs and local food artisans. A paradise for food lovers.',
    date: '2024-09-05T12:00:00Z',
    time: '12:00 PM',
    location: 'City Central Plaza',
    category: 'Food',
    price: 25.00,
    imageUrl: 'https://picsum.photos/seed/foodfair/600/400',
    imageHint: 'food fair',
    organizer: 'TasteMakers Inc.',
    vendorId: 'vendor-02',
    status: 'approved',
  },
  {
    id: 'evt-003',
    name: 'Future of Tech Summit',
    description: 'Join industry leaders and innovators to discuss the future of AI, blockchain, and sustainable tech.',
    date: '2024-10-20T09:00:00Z',
    time: '9:00 AM',
    location: 'Metropolis Convention Center',
    category: 'Tech',
    price: 199.00,
    imageUrl: 'https://picsum.photos/seed/techsummit/600/400',
    imageHint: 'tech conference',
    organizer: 'InnovateSphere',
    vendorId: 'vendor-03',
    status: 'approved',
  },
  {
    id: 'evt-004',
    name: 'Abstract Art Exhibition: "Dimensions"',
    description: 'A curated collection of mind-bending abstract art from emerging and established artists.',
    date: '2024-09-12T11:00:00Z',
    time: '11:00 AM',
    location: 'The Modern Art Gallery',
    category: 'Arts',
    price: 15.00,
    imageUrl: 'https://picsum.photos/seed/artexhibit/600/400',
    imageHint: 'art gallery',
    organizer: 'Canvas & Clay',
    vendorId: 'vendor-04',
    status: 'approved',
  },
  {
    id: 'evt-005',
    name: 'City Marathon 2024',
    description: 'Run through the heart of the city in our annual marathon. All skill levels are welcome!',
    date: '2024-11-03T07:00:00Z',
    time: '7:00 AM',
    location: 'Downtown Start Line',
    category: 'Sports',
    price: 50.00,
    imageUrl: 'https://picsum.photos/seed/marathon/600/400',
    imageHint: 'marathon running',
    organizer: 'City Sports Commission',
    vendorId: 'vendor-05',
    status: 'approved',
  },
  {
    id: 'evt-006',
    name: 'Indie Film Festival',
    description: 'Discover the next generation of filmmakers. Screenings, Q&As, and networking events.',
    date: '2024-09-25T13:00:00Z',
    time: '1:00 PM',
    location: 'The Grand Cinema',
    category: 'Arts',
    price: 40.00,
    imageUrl: 'https://picsum.photos/seed/filmfest/600/400',
    imageHint: 'film festival',
    organizer: 'Reel Dreams',
    vendorId: 'vendor-04',
    status: 'approved',
  },
  {
    id: 'evt-007',
    name: 'Rock Climbing Workshop',
    description: 'Learn the basics of rock climbing from certified instructors. Equipment provided.',
    date: '2024-08-22T10:00:00Z',
    time: '10:00 AM',
    location: 'Ascend Climbing Gym',
    category: 'Sports',
    price: 60.00,
    imageUrl: 'https://picsum.photos/seed/rockclimbing/600/400',
    imageHint: 'rock climbing',
    organizer: 'City Sports Commission',
    vendorId: 'vendor-05',
    status: 'pending',
  },
  {
    id: 'evt-008',
    name: 'Jazz Night at the Speakeasy',
    description: 'A smooth evening of classic jazz, craft cocktails, and vintage vibes.',
    date: '2024-09-01T20:00:00Z',
    time: '8:00 PM',
    location: 'The Velvet Note',
    category: 'Music',
    price: 30.00,
    imageUrl: 'https://picsum.photos/seed/jazznight/600/400',
    imageHint: 'jazz club',
    organizer: 'SoundWave Productions',
    vendorId: 'vendor-01',
    status: 'approved',
  },
  {
    id: 'evt-009',
    name: 'AI for Developers Conference',
    description: 'A deep-dive into practical AI applications, machine learning models, and development tools.',
    date: '2024-11-15T09:30:00Z',
    time: '9:30 AM',
    location: 'Metropolis Convention Center',
    category: 'Tech',
    price: 250.00,
    imageUrl: 'https://picsum.photos/seed/aidevs/600/400',
    imageHint: 'developer conference',
    organizer: 'InnovateSphere',
    vendorId: 'vendor-03',
    status: 'rejected',
  },
  {
    id: 'evt-010',
    name: 'International Street Food Festival',
    description: 'Taste the world in one place! A vibrant celebration of street food from every corner of the globe.',
    date: '2024-10-12T11:00:00Z',
    time: '11:00 AM',
    location: 'The Waterfront Esplanade',
    category: 'Food',
    price: 10.00,
    imageUrl: 'https://picsum.photos/seed/streetfood/600/400',
    imageHint: 'street food',
    organizer: 'TasteMakers Inc.',
    vendorId: 'vendor-02',
    status: 'approved',
  },
];

export const userTickets: Ticket[] = [
    {
      id: 'tkt-001',
      eventId: 'evt-001',
      userId: 'user-01',
      purchaseDate: '2024-07-20T10:00:00Z',
      price: 75.00,
      isUsed: false,
    },
    {
      id: 'tkt-002',
      eventId: 'evt-004',
      userId: 'user-01',
      purchaseDate: '2024-07-22T14:30:00Z',
      price: 15.00,
      isUsed: false,
    },
];

export const vendorEvents: VendorEvent[] = [
  {
    ...sampleEvents.find(e => e.id === 'evt-001')!,
    ticketsSold: 250,
    revenue: 18750,
  },
  {
    ...sampleEvents.find(e => e.id === 'evt-008')!,
    ticketsSold: 80,
    revenue: 2400,
  },
];
