
import type { Event, Ticket, VendorEvent } from '@/lib/types';

const storageBaseUrl = 'https://firebasestorage.googleapis.com/v0/b/studio-8569439258-4b916.firebasestorage.app/o/public%2Fassets%2F';
const storageToken = 'alt=media';

export const sampleEvents: Event[] = [
  {
    id: '1',
    name: 'Global Music Fest 2024',
    description: 'Experience the best music from around the world.',
    date: '2024-10-26',
    time: '18:00',
    location: 'Grand Park, New York',
    category: 'Music',
    price: 75.00,
    organizer: 'MusicMakers Inc.',
    imageUrl: `${storageBaseUrl}event-1.jpg?${storageToken}`,
    imageHint: 'concert music',
  },
  {
    id: '2',
    name: 'Future of Art Exhibition',
    description: 'A journey into the future of digital and physical art.',
    date: '2024-11-15',
    time: '10:00',
    location: 'Metropolis Art Gallery',
    category: 'Arts',
    price: 25.00,
    organizer: 'ArtVisionaries',
    imageUrl: `${storageBaseUrl}event-2.jpg?${storageToken}`,
    imageHint: 'art gallery',
  },
  {
    id: '3',
    name: 'Innovate & Create Tech Summit',
    description: 'Join leaders in tech to discuss the future of innovation.',
    date: '2024-09-05',
    time: '09:00',
    location: 'Silicon Valley Convention Center',
    category: 'Tech',
    price: 199.00,
    organizer: 'TechForward',
    imageUrl: `${storageBaseUrl}event-3.jpg?${storageToken}`,
    imageHint: 'tech conference',
  },
  {
    id: '4',
    name: 'Gourmet Bites Festival',
    description: 'A weekend of delicious food, drinks, and fun.',
    date: '2024-09-21',
    time: '12:00',
    location: 'Downtown Food Plaza',
    category: 'Food',
    price: 40.00,
    organizer: 'TasteMasters',
    imageUrl: `${storageBaseUrl}event-4.jpg?${storageToken}`,
    imageHint: 'food festival',
  },
  {
    id: '5',
    name: 'Sunrise Yoga Retreat',
    description: 'Find your inner peace with a refreshing morning of yoga.',
    date: '2024-10-05',
    time: '06:00',
    location: 'Serenity Beach',
    category: 'Sports',
    price: 30.00,
    organizer: 'ZenLife',
    imageUrl: `${storageBaseUrl}event-5.jpg?${storageToken}`,
    imageHint: 'yoga class',
  },
  {
    id: '6',
    name: 'Indie Rock Night',
    description: 'Discover the best new bands in the indie rock scene.',
    date: '2024-11-01',
    time: '20:00',
    location: 'The Underground Venue',
    category: 'Music',
    price: 20.00,
    organizer: 'LiveLoud',
    imageUrl: `${storageBaseUrl}event-6.jpg?${storageToken}`,
    imageHint: 'rock band',
  },
  {
    id: '7',
    name: 'Modern Sculptures Unveiled',
    description: 'An exclusive look at the work of contemporary sculptors.',
    date: '2024-10-12',
    time: '19:00',
    location: 'City Sculpture Park',
    category: 'Arts',
    price: 15.00,
    organizer: 'ArtVisionaries',
    imageUrl: `${storageBaseUrl}event-7.jpg?${storageToken}`,
    imageHint: 'painting exhibition',
  },
  {
    id: '8',
    name: 'Startup Showcase 2024',
    description: 'The brightest new startups pitch their ideas.',
    date: '2024-11-20',
    time: '14:00',
    location: 'Innovation Hub',
    category: 'Tech',
    price: 50.00,
    organizer: 'TechForward',
    imageUrl: `${storageBaseUrl}event-8.jpg?${storageToken}`,
    imageHint: 'startup pitch',
  },
];

export const userTickets: Ticket[] = [
  {
    id: 'tkt-1',
    event: sampleEvents[0],
    purchaseDate: '2024-08-15',
  },
  {
    id: 'tkt-2',
    event: sampleEvents[2],
    purchaseDate: '2024-07-30',
  },
  {
    id: 'tkt-3',
    event: sampleEvents[4],
    purchaseDate: '2024-09-01',
  },
];

export const vendorEvents: VendorEvent[] = [
  { ...sampleEvents[1], ticketsSold: 250, revenue: 6250 },
  { ...sampleEvents[3], ticketsSold: 120, revenue: 4800 },
];
